"""SimTX bridge interface for ZevGSM.

No real GSM RF is generated by v0.1. This layer will later connect the
ZevGSM packet protocol to an audio/IQ modem and SimTX transport.
"""

from __future__ import annotations
from collections.abc import Callable
from packets import Packet

class SimTXAdapter:
    def __init__(self, send_radio: Callable[[bytes], None] | None = None):
        self.send_radio = send_radio

    def transmit(self, packet: Packet) -> None:
        if self.send_radio is None:
            raise RuntimeError("SimTX radio transport is not configured")
        self.send_radio(packet.encode())

    def receive(self, data: bytes) -> Packet:
        return Packet.decode(data)
